# Powerlevel10k — Rainbow Blocks (compact)
# Requires MesloLGS NF (installed by your bootstrap)
# Drop-in file: ~/.p10k.zsh or dotfiles/p10k.zsh

# Speed & Fonts
typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet
typeset -g POWERLEVEL9K_MODE='nerdfont-complete'

# Two-line prompt with powerline separators
typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=false
typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=''
typeset -g POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_PREFIX=''
typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX=''

# Powerline separators (rainbow blocks)
typeset -g POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=''
typeset -g POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=''
typeset -g POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR=''
typeset -g POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR=''
typeset -g POWERLEVEL9K_LEFT_PROMPT_FIRST_SEGMENT_START_SYMBOL=''
typeset -g POWERLEVEL9K_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=''
typeset -g POWERLEVEL9K_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL=''
typeset -g POWERLEVEL9K_RIGHT_PROMPT_LAST_SEGMENT_END_SYMBOL=''

# Prompt elements
typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
  os_icon
  dir
  vcs
  newline
  prompt_char
)
typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
  status
  command_execution_time
  background_jobs
  virtualenv
  node_version
  time
)

# Colors per segment (rainbow order)
# os_icon: purple
typeset -g POWERLEVEL9K_OS_ICON_BACKGROUND=93
typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND=232
typeset -g POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION='%F{232}%f'  # on macOS; harmless elsewhere

# dir: blue
typeset -g POWERLEVEL9K_DIR_BACKGROUND=33
typeset -g POWERLEVEL9K_DIR_FOREGROUND=255
typeset -g POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique
typeset -g POWERLEVEL9K_DIR_MAX_LENGTH=3
typeset -g POWERLEVEL9K_DIR_TRUNCATE_BEFORE_MARKER=false

# vcs: green/yellow depending on state
typeset -g POWERLEVEL9K_VCS_CLEAN_BACKGROUND=70
typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=232
typeset -g POWERLEVEL9K_VCS_MODIFIED_BACKGROUND=178
typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=232
typeset -g POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND=39
typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=232
typeset -g POWERLEVEL9K_VCS_CONFLICTED_BACKGROUND=196
typeset -g POWERLEVEL9K_VCS_CONFLICTED_FOREGROUND=232
typeset -g POWERLEVEL9K_VCS_BRANCH_ICON=' '
typeset -g POWERLEVEL9K_VCS_UNTRACKED_ICON='?'
typeset -g POWERLEVEL9K_VCS_BACKENDS=(git)

# prompt_char: pink
typeset -g POWERLEVEL9K_PROMPT_CHAR_BACKGROUND=199
typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_CONTENT_EXPANSION='❯'
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_VIINS_CONTENT_EXPANSION='❯'
typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_VICMD_CONTENT_EXPANSION='❮'
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_VICMD_CONTENT_EXPANSION='❮'
typeset -g POWERLEVEL9K_PROMPT_CHAR_OVERWRITE_STATE=true
typeset -g POWERLEVEL9K_PROMPT_CHAR_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=''  # keep block end neat

# status: red on error, hidden on success (block still flows)
typeset -g POWERLEVEL9K_STATUS_EXTENDED_STATES=true
typeset -g POWERLEVEL9K_STATUS_OK=false
typeset -g POWERLEVEL9K_STATUS_ERROR=true
typeset -g POWERLEVEL9K_STATUS_ERROR_BACKGROUND=160
typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=255
typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL=true
typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_BACKGROUND=160
typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_FOREGROUND=255
typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE=true
typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_BACKGROUND=160
typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_FOREGROUND=255

# command_execution_time: orange
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND=208
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=232
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=3
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=0
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FORMAT='d h m s'

# background_jobs: teal
typeset -g POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND=30
typeset -g POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND=255
typeset -g POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE=false

# virtualenv: cyan
typeset -g POWERLEVEL9K_VIRTUALENV_BACKGROUND=39
typeset -g POWERLEVEL9K_VIRTUALENV_FOREGROUND=232
typeset -g POWERLEVEL9K_VIRTUALENV_SHOW_PYTHON_VERSION=false
typeset -g POWERLEVEL9K_VIRTUALENV_SHOW_WITH_PYENV=false

# node_version: green (project-only)
typeset -g POWERLEVEL9K_NODE_VERSION_BACKGROUND=70
typeset -g POWERLEVEL9K_NODE_VERSION_FOREGROUND=232
typeset -g POWERLEVEL9K_NODE_VERSION_PROJECT_ONLY=true

# time: gray
typeset -g POWERLEVEL9K_TIME_BACKGROUND=238
typeset -g POWERLEVEL9K_TIME_FOREGROUND=255
typeset -g POWERLEVEL9K_TIME_FORMAT='%D{%H:%M}'

# Transient prompt (collapse after you hit Enter)
typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=always

# Make sure p10k reloads if already loaded
(( ! $+functions[p10k] )) || p10k reload
